version: '2'
services:
  squid-ssl-bump:
    build: ./squid-ssl-bump
    container_name: squid-ssl-bump
    ports:
     - "3128:3128"
     - "3129:3129"

  squid:
    build: ./squid
    container_name: squid
